import type { AgentManifest } from "@/lib/agent/manifest";

/**
 * DemoStep — a scripted AgentManifest plus how long to dwell on it before the
 * demo provider advances to the next step.
 */
export interface DemoStep extends AgentManifest {
  id: string;
  durationMs: number;
}

/**
 * Scripted walkthrough of all three modules — Cook (Auditor), Order (Scout),
 * Dine (Negotiator) — each carrying a real two-exchange back-and-forth
 * (ask → answer, follow-up → confirm) instead of a single Q&A, and voiced in
 * the actual Kitchen Copilot persona from agent/prompts/system.md (opinion +
 * one-line reason, contractions, no chatbot tics).
 *
 * "Thinking" beats intentionally carry no `agentSays` — the system prompt's
 * voice contract explicitly bans narrating tool calls ("Let me check…",
 * "Pulling that up…"); the real agent just goes quiet and then speaks the
 * result, so the demo does too.
 *
 * Each closing beat is split into TWO steps: a spoken line (`agentSays`,
 * no `confirm`), then a separate receipt step (`confirm`, no `agentSays`).
 * The ConfirmCard's layout (app/voice/page.tsx) assumes the caption has
 * already cleared by the time the receipt renders — true in live mode,
 * where captions clear on `response.done` before a tool result lands — so
 * setting both on the same step overlaps the caption text with the card.
 *
 * No em dashes in any spoken or on-screen line — spell pauses out as
 * separate sentences instead.
 *
 * Every step with `agentSays` has a matching spoken clip at
 * `public/demo-audio/{id}.wav` (git-ignored, generated by
 * `npm run generate:demo-audio` against the real gpt-realtime + sage voice
 * over the Realtime WebSocket API — not the standalone TTS endpoint, which
 * sounds noticeably different). If you edit an `agentSays` line, re-run that
 * script with `--force` and re-check `durationMs` against the printed clip
 * length so playback isn't cut off mid-sentence.
 */
export const DEMO_SCRIPT: DemoStep[] = [
  // ---------- OPENING — the Intent Gateway ----------
  {
    id: "gateway",
    intent: "idle",
    aura: "speaking",
    agentSays: "Hey. Are we cooking tonight, ordering in, or heading out?",
    durationMs: 4700, // matches spoken audio length, see public/demo-audio/
  },

  // ---------- COOKING flow (Auditor) ----------
  {
    id: "cook-intro",
    intent: "cook",
    aura: "idle",
    userSays: "Let's cook tonight. Pasta carbonara for two.",
    durationMs: 2400,
  },
  {
    id: "cook-listen",
    intent: "cook",
    aura: "listening",
    userSays: "Let's cook tonight. Pasta carbonara for two.",
    durationMs: 2200,
  },
  {
    id: "cook-think",
    intent: "cook",
    aura: "thinking",
    durationMs: 1500,
  },
  {
    id: "cook-show",
    intent: "cook",
    aura: "speaking",
    agentSays:
      "You're short three things: pancetta, pecorino, and black pepper. Heads up, pancetta only comes in two-hundred gram packs, more than you need, but that's the smallest size.",
    cards: [
      {
        kind: "instamart",
        id: "im-pancetta",
        name: "Pancetta",
        reason: "You asked for 120g. Smallest pack is 200g pack.",
        pack: "200g pack",
        price: 420,
        imageHue: 12,
      },
      {
        kind: "instamart",
        id: "im-pecorino",
        name: "Pecorino Romano",
        reason: "You asked for 80g. Smallest pack is 150g block.",
        pack: "150g block",
        price: 385,
        imageHue: 50,
      },
      {
        kind: "instamart",
        id: "im-peppercorns",
        name: "Black Peppercorns",
        reason: "You asked for a pinch. Smallest pack is 50g jar.",
        pack: "50g jar",
        price: 95,
        imageHue: 28,
      },
    ],
    durationMs: 13000, // matches spoken audio length, see public/demo-audio/
  },
  {
    id: "cook-followup-user",
    intent: "cook",
    aura: "idle",
    userSays: "That works, throw it all in. Anything else I'm missing?",
    durationMs: 2600,
  },
  {
    id: "cook-followup-listen",
    intent: "cook",
    aura: "listening",
    userSays: "That works, throw it all in. Anything else I'm missing?",
    durationMs: 2400,
  },
  {
    id: "cook-confirm",
    intent: "cook",
    aura: "success",
    agentSays: "Nope, that's everything. Adding it now, twelve minutes out.",
    cards: [
      {
        kind: "instamart",
        id: "im-pancetta",
        name: "Pancetta",
        reason: "You asked for 120g. Smallest pack is 200g pack.",
        pack: "200g pack",
        price: 420,
        imageHue: 12,
        state: "added",
      },
      {
        kind: "instamart",
        id: "im-pecorino",
        name: "Pecorino Romano",
        reason: "You asked for 80g. Smallest pack is 150g block.",
        pack: "150g block",
        price: 385,
        imageHue: 50,
        state: "added",
      },
      {
        kind: "instamart",
        id: "im-peppercorns",
        name: "Black Peppercorns",
        reason: "You asked for a pinch. Smallest pack is 50g jar.",
        pack: "50g jar",
        price: 95,
        imageHue: 28,
        state: "added",
      },
    ],
    durationMs: 5000, // matches spoken audio length, see public/demo-audio/
  },
  {
    id: "cook-receipt",
    intent: "cook",
    aura: "success",
    cards: [
      {
        kind: "instamart",
        id: "im-pancetta",
        name: "Pancetta",
        reason: "You asked for 120g. Smallest pack is 200g pack.",
        pack: "200g pack",
        price: 420,
        imageHue: 12,
        state: "added",
      },
      {
        kind: "instamart",
        id: "im-pecorino",
        name: "Pecorino Romano",
        reason: "You asked for 80g. Smallest pack is 150g block.",
        pack: "150g block",
        price: 385,
        imageHue: 50,
        state: "added",
      },
      {
        kind: "instamart",
        id: "im-peppercorns",
        name: "Black Peppercorns",
        reason: "You asked for a pinch. Smallest pack is 50g jar.",
        pack: "50g jar",
        price: 95,
        imageHue: 28,
        state: "added",
      },
    ],
    confirm: { title: "3 items · ₹900", subtitle: "Arrives in 12 min" },
    durationMs: 2800,
  },

  // ---------- ORDERING flow (Scout) ----------
  {
    id: "order-intro",
    intent: "order",
    aura: "idle",
    userSays: "Actually, change of plans. Order me something Thai, I don't feel like cooking anymore.",
    durationMs: 3000,
  },
  {
    id: "order-listen",
    intent: "order",
    aura: "listening",
    userSays: "Actually, change of plans. Order me something Thai, I don't feel like cooking anymore.",
    durationMs: 2800,
  },
  {
    id: "order-think",
    intent: "order",
    aura: "thinking",
    durationMs: 1500,
  },
  {
    id: "order-show",
    intent: "order",
    aura: "speaking",
    agentSays:
      "Soi 38's the move. Their pad kee mao with prawns is unreal, twenty-four minutes out. House of Lemongrass is solid too if you want something a bit fancier.",
    cards: [
      {
        kind: "restaurant",
        id: "res-soi-38",
        name: "Soi 38",
        cuisine: "Bangkok street food · 1.2 km",
        rating: 4.6,
        etaMinutes: 24,
        price: 540,
        imageHue: 30,
        agentPick: { item: "Pad kee mao with prawns", price: 540 },
      },
      {
        kind: "restaurant",
        id: "res-lemongrass",
        name: "House of Lemongrass",
        cuisine: "Modern Thai · 2.1 km",
        rating: 4.4,
        etaMinutes: 28,
        price: 680,
        imageHue: 18,
        agentPick: { item: "Massaman lamb shank", price: 680 },
      },
    ],
    durationMs: 10400, // matches spoken audio length, see public/demo-audio/
  },
  {
    id: "order-pick-user",
    intent: "order",
    aura: "idle",
    userSays: "Let's do Soi 38. Get me the pad kee mao.",
    durationMs: 2200,
  },
  {
    id: "order-pick-listen",
    intent: "order",
    aura: "listening",
    userSays: "Let's do Soi 38. Get me the pad kee mao.",
    durationMs: 2000,
  },
  {
    id: "order-confirm",
    intent: "order",
    aura: "success",
    agentSays: "Good call. Ordering now, Rohan's on it, twenty-four minutes.",
    cards: [
      {
        kind: "delivery",
        status: "Soi 38 · preparing your order",
        etaMinutes: 24,
        progress: 0.18,
        stage: "prep",
      },
    ],
    durationMs: 5300, // matches spoken audio length, see public/demo-audio/
  },
  {
    id: "order-progress2",
    intent: "order",
    aura: "idle",
    cards: [
      {
        kind: "delivery",
        status: "Rohan is on the way",
        etaMinutes: 11,
        progress: 0.68,
        stage: "route",
      },
    ],
    durationMs: 2600,
  },

  // ---------- DINING OUT flow (Negotiator) ----------
  {
    id: "dine-intro",
    intent: "dine",
    aura: "idle",
    userSays: "Book us a table at Olive, eight tonight.",
    durationMs: 2400,
  },
  {
    id: "dine-listen",
    intent: "dine",
    aura: "listening",
    userSays: "Book us a table at Olive, eight tonight.",
    durationMs: 2200,
  },
  {
    id: "dine-think",
    intent: "dine",
    aura: "thinking",
    durationMs: 1500,
  },
  {
    id: "dine-negotiate",
    intent: "dine",
    aura: "speaking",
    agentSays:
      "Ugh, eight's gone everywhere over there. I can grab you seven-fifteen, or a forty-five minute wait for eight-forty-five. But honestly, Toscano's got eight-thirty open, four minutes away, same vibe. Might be the better call.",
    negotiator: {
      headline: "8:00 at Olive Bistro is full.",
      restaurantStrikethrough: "Olive Bistro",
      slots: [
        {
          time: "7:15",
          label: "EARLIER",
          available: true,
          rationale: {
            headline: "Earlier slot, same restaurant",
            note: "You'd skip the late-evening crowd. Sunset terrace seating likely.",
          },
        },
        {
          time: "8:00",
          label: "REQUESTED",
          available: false,
        },
        {
          time: "8:45",
          label: "+45 MIN",
          available: true,
          rationale: {
            headline: "Same restaurant, slight wait",
            note: "Olive has a 45-minute opening on the patio. Similar buzz to your usual.",
          },
        },
        {
          time: "8:30",
          label: "SIMILAR VIBE",
          available: true,
          restaurant: "Toscano",
          rationale: {
            headline: "Toscano, 4 min walk, same vibe",
            note: "Modern Italian, comparable wine list. 4.5★ from your regulars.",
          },
        },
      ],
      focusedSlotIndex: 3,
      state: "choosing",
    },
    durationMs: 16400, // matches spoken audio length, see public/demo-audio/
  },
  {
    id: "dine-pick-user",
    intent: "dine",
    aura: "idle",
    userSays: "Let's do Toscano, eight-thirty works.",
    durationMs: 2200,
  },
  {
    id: "dine-pick-listen",
    intent: "dine",
    aura: "listening",
    userSays: "Let's do Toscano, eight-thirty works.",
    durationMs: 2000,
  },
  {
    id: "dine-confirm",
    intent: "dine",
    aura: "success",
    agentSays: "Done. Toscano, eight-thirty, table for two. Want me to flag a dessert spot for after, or you're good?",
    durationMs: 7600, // matches spoken audio length, see public/demo-audio/
  },
  {
    id: "dine-receipt",
    intent: "dine",
    aura: "success",
    confirm: { title: "Toscano · 8:30 PM", subtitle: "Table for 2 confirmed" },
    durationMs: 2800,
  },
];
